# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    require_trailing_commas: ignore
    sort_constructors_first: ignore
    unnecessary_lambdas: ignore
